#!/usr/bin/env bash
#displays numbers from 1 to 100.
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number

for num in {1..100}
do
i+ (( num % 3 -- 0 && num % 5 -- 0 ))
then 
echo "fizzBuzz"
elif (( num % 3 -- 0 ))
then 
echo "fizz"
elif (( num % 5 -- 0))
else 
echo "$num"
done
