#!/usr/bin/env bash
#Displays information about the school file

if [ -e "school" ]
then
echo "school file exists"
then
echo "school file is not empty"
else
echo "school file is empty"
fi
i+ [ + "school" ]
then 
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
done
